Removed eval + fixed all flag set with t=-1

diff --git a/grab b/grab
--- a/grab
+++ b/grab
@@ -1,4 +1,14 @@
 #!/bin/bash
+
+check_required_utilities() {
+for cmd in awk find mv xargs ls rm head basename; do
+  if ! command -v "$cmd" &> /dev/null; then
+    printf "Error: %s is not installed.\n" "$cmd"
+    return 1
+  fi
+done
+}
+
 # Initialize default configurations 
 initialize_default_configs() {
   cat <<EOL > "$1"
@@ -16,15 +26,8 @@ read_value_from_file() {
 }
 
 grab() {
-  # Check for required utilities
-  for cmd in awk find mv; do
-    if ! command -v $cmd &> /dev/null; then
-      printf "Error: %s is not installed.\n" "$cmd"
-      return 1
-    fi
-  done
 
-  local all_flag=false
+  local move_all_flag=false
   local list_flag=false
   local delete_flag=false
   local permissions_file="$HOME/.grab_config"
@@ -42,32 +45,33 @@ grab() {
   fi
 
   # Read and validate config values
-  local time_limit=$(read_value_from_file "$permissions_file" "time")
+  local time_limit_minutes=$(read_value_from_file "$permissions_file" "time")
   local default_downloads_dir=$(read_value_from_file "$permissions_file" "downloads_dir")
 
-  if [ -z "$time_limit" ] || [ -z "$default_downloads_dir" ]; then
+  if [ -z "$time_limit_minutes" ] || [ -z "$default_downloads_dir" ]; then
     printf "Error: Configuration file %s is malformed. It must contain valid 'time' and 'downloads_dir' keys.\n" "$permissions_file"
 
     return 1
   fi
-  
-  eval default_downloads_dir="$default_downloads_dir"
+ 
+  # Changed full path expansion to manual tilde expansion due to tilde read from files not expanding.
+  default_downloads_dir="${default_downloads_dir/#\~/$HOME}"
 
   if [ ! -d "$default_downloads_dir" ]; then
-  printf "Downloads directory %s does not exist.\n" "$default_downloads_dir"
+  printf "Downloads directory '%s' does not exist.\n" "$default_downloads_dir"
 
   return 1
-fi
+  fi
 
   local file_count=0
   local find_command
 
   while getopts "alxt:" opt; do
     case $opt in
-      a) all_flag=true ;;
+      a) move_all_flag=true ;;
       l) list_flag=true ;;
       x) delete_flag=true ;;
-      t) time_limit=$OPTARG ;;
+      t) time_limit_minutes=$OPTARG ;;
       *) printf "Invalid option.\n"; return 1 ;;
 
     esac
@@ -75,8 +79,15 @@ fi
   shift $((OPTIND - 1))
 
   # Validate time limit
-  if ! [[ "$time_limit" =~ ^-1$ ]] && ! [[ "$time_limit" =~ ^[0-9]+$ ]]; then
+  if ! [[ "$time_limit_minutes" =~ ^-1$ ]] && ! [[ "$time_limit_minutes" =~ ^[0-9]+$ ]]; then
     printf "Error: Invalid time limit.\n"
+
+    return 1
+  fi
+
+  # Prevents someone from grabbing their entire downloads folder
+  if [ "$move_all_flag" = true ] &&  [[ "$time_limit_minutes" =~ ^-1$ ]]; then
+    printf "Error: Cannot use 'all' flag with time '-1'.\n"
 
     return 1
   fi
@@ -110,13 +121,13 @@ fi
     file_operation="mv"
   fi
 
-  if [ "$time_limit" -eq -1 ]; then
-    find_command="find \"$default_downloads_dir\" -maxdepth 1 -type f"
+  if [ "$time_limit_minutes" -eq -1 ]; then
+    find_command=(find "$default_downloads_dir" -maxdepth 1 -type f)
   else
-    find_command="find \"$default_downloads_dir\" -maxdepth 1 -type f -mmin \"-$time_limit\""
+    find_command=(find "$default_downloads_dir" -maxdepth 1 -type f -mmin -"$time_limit_minutes")
   fi
 
-  if [ "$all_flag" = true ]; then
+  if [ "$move_all_flag" = true ]; then
     file_count=0
     while read -r file; do
       if [ "$delete_flag" = false ]; then
@@ -126,9 +137,9 @@ fi
       fi
       ((file_count++))
       [ "$list_flag" = true ] && printf "%s: %s\n" "$action" "$(basename "$file")"
-    done < <(eval "$find_command")
+    done < <("${find_command[@]}")
     if [ "$file_count" -eq 0 ]; then
-      printf "No recent files found in Downloads directory within the last %d minutes.\n" "$time_limit"
+      printf "No recent files found in Downloads directory within the last %d minutes.\n" "$time_limit_minutes"
     elif [ "$delete_flag" = false ]; then
     [ "$list_flag" = false ] && printf "%s %d file(s) to %s.\n" "$action" "$file_count" "$display_destination"
     else
@@ -136,11 +147,10 @@ fi
     fi
 
   else
-    local newest_file=$(eval "$find_command" -exec ls -lt {} + | head -n 1 | awk '{for(i=9;i<=NF;++i) printf $i (i==NF?ORS:OFS)}')
-
+    local newest_file=$( "${find_command[@]}" | xargs -I {} ls -lt "{}" | head -n 1 | awk '{for(i=9;i<=NF;++i) printf $i (i==NF?ORS:OFS)}' )
 
     if [ -z "$newest_file" ]; then
-      printf "No recent files found in Downloads directory within the last %d minutes.\n" "$time_limit"
+      printf "No recent files found in Downloads directory within the last %d minutes.\n" "$time_limit_minutes"
 
       return 1
     fi
@@ -155,4 +165,5 @@ fi
     fi
   fi
 }
+check_required_utilities
 grab "$@"
